# Generated by Django 2.0.3 on 2018-03-19 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInstances',
            new_name='BookInstance',
        ),
    ]
